[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    "Content-Security-Policy" = "default-src 'self' https://kennygoff.com https://www.kennygoff.com https://calm-thorn-side.kennygoff.com;"
