[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  targetPort = 3000

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31560000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "Content-Security-Policy" = "default-src 'self' https://kennygoff.com https://www.kennygoff.com https://calm-thorn-side.kennygoff.com https://cdn.usefathom.com;"
